steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'forum', '--runtime=nodejs8', '--trigger-http', '--entry-point=app']